---
# tasks file for apache
- name: Installation apache
  yum:
   name: httpd
   state: present

- name: disable firewall
  systemd:
   name: firewalld
   state: stopped
   enabled: no

- name: Création des répertoires des sites
  file: 
   path: /var/www/{{ item }}
   state: directory
   mode: '0755'
   owner: root
   group: root
   recurse: yes
  loop:
    "{{ sites }}"

- name: Création du template de fichier de conf
  template:
   src: conf.j2
   dest: /etc/httpd/conf.d/{{ item }}.conf
  loop:
    "{{ sites }}"

- name: démarrage et activation du serveur apache
  systemd:
   name: httpd
   state: started
   enabled: yes

