---
# tasks file for apache
- name: Installation apache 
  yum:
   name: httpd
   state: present

- name: arret pare feu
  systemd:
   name: firewalld
   state: stopped
   enabled: no

- name: Création des répertoires des différents sites
  file: 
   path: /var/www/{{ item }}
   state: directory
   mode: '0755'
   owner: root
   group: root
   recurse: yes
  loop:
    "{{ sites }}"

- name: Création du template 
  template:
   src: configuration.j3
   dest: /etc/httpd/conf.d/{{ item }}.conf
  loop:
    "{{ sites }}"

- name: php
  copy:
   src: app-php/
   dest: /var/www/{{ item }}/html/
  loop:
    "{{ sites }}"

- name: démarrage et activation du serveur apache
  systemd:
   name: httpd
   state: started
   enabled: yes
